### ISSUE TITLE
Rules & Guidelines

### ISSUE THREAD

**Issue by kishanrajput23** [kishanrajput23/Awesome-Project-Collection#2]
Hello folks, 
Let's begin your contribution journey✈️

## Rules you should follow to be eligible for a valid PR contender :
1. Make sure you star this repository. 
2. Create a new branch and don't directly commit into main branch. 
3. Now create a folder of your project name then add your all source codes in it. 
4. Add README.md file in project folder. (Mandatory) 
5. In README.md file add all the screen shots of your project if your project is web bases otherwise add your project output screen shots. 
6. Commit the changes and create new PR. 
7. Now just wait for your PR to be reviewed. 
8. After reviewing your PR I'll merge it as soon as possible. 

## Don't do this :
1. If you don't adhere above rules then sorry I'll not merge your PR. 
2. Spamming the repository is strictly prohibited. 
3. If I found someone who's doing spamming I'll directly add invalid or spam tag in his/her PR. Then you'll directly get disqualified by Hacktoberfest. 

Happy Contribution Ahead 👍

**Comment by maitreypatadia** [comment]
Hello, I want to contribute to this issue but where is the hactoberfest label?

**Comment by kishanrajput23** [comment]
@maitreypatadia check repository home page right corner you'll see two tags over there.

**Comment by maitreypatadia** [comment]
ya got it. Thanks :-)

**Comment by nitishgiri007** [comment]
Hello sir I really want to contribute on this issue please provide me this repo

**Comment by swarnavadas-003** [comment]
Other than website may i add an app UI?

**Comment by kishanrajput23** [comment]
yes @swarnavadas-003

**Comment by kishanrajput23** [comment]
go ahead @nitishgiri007

**Comment by jyotika6221** [comment]
I want to contribute to this issue, kindly assign me please.

**Comment by shashank-adiga** [comment]
I would like to contribute to this issue, kindly assign the repo

**Comment by pranit9000** [comment]
I want to contribute to this issue, kindly assign me.

**Comment by Kriti1262** [comment]
I want to contribute to this repository .Please sir kindly assign me.

**Comment by saimafirdousfh** [comment]
Can i contribute

**Comment by yxshrraj** [comment]
I want to contribute to this issue . Please assign me sir

**Comment by Sanskrutiii** [comment]
Hello sir, can you assign this issue to me?
